# Generated by Django 6.0 on 2026-01-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('started', '0016_alter_room_latitude_alter_room_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='started.owner'),
            preserve_default=False,
        ),
    ]
